In [3]:
import torch 

In [8]:
a = torch.zeros((2,2, 2))
b = torch.ones((2,2, 2))
c = b + b

In [18]:
torch.cat((a,b,c))

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])

In [15]:
torch.cat((a,b,c)).reshape(-1, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])

In [19]:
torch.cat((a,b,c)) == torch.cat((a,b,c)).reshape(-1, 2).reshape(6, 2, 2)

tensor([[[True, True],
         [True, True]],

        [[True, True],
         [True, True]],

        [[True, True],
         [True, True]],

        [[True, True],
         [True, True]],

        [[True, True],
         [True, True]],

        [[True, True],
         [True, True]]])

In [4]:
import torch.nn as nn 
import torch 
class conv_norm_relu(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=1, padding=1)
        self.norm1 = nn.InstanceNorm2d(out_channels)
        self.relu1 = nn.ReLU(inplace=True) # Doesn't create a new tensor for the output.
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1)
        self.norm2 = nn.InstanceNorm2d(out_channels)
        self.relu2 = nn.ReLU(inplace=True) # For saving memory

    def forward(self, x):
        out = self.conv1(x)
        out = self.norm1(out)
        out = self.relu1(out)
        out = self.conv2(out)
        out = self.norm2(out)
        out = self.relu2(out)
        return out

In [13]:
class encoder_block(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = conv_norm_relu(in_channels,out_channels)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        
    def forward(self, x):
        x = self.conv(x)
        # p = self.pool(x)
        return x

In [14]:
a = torch.rand((1, 1,128,128))
encoder = encoder_block(in_channels=1,out_channels=64)
b = encoder(a)
b.shape

torch.Size([1, 64, 128, 128])

In [ ]:
b.shape